import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

type PatientTrialData = Record<string, any>;

export async function generatePatientTrialReport(patientData: PatientTrialData, patientName: string) {
  function getCurrentEmail(): string {
    if (typeof window === 'undefined') return 'Unknown';
    const authRaw = window.localStorage.getItem('laminitis_auth_state');
    try {
      const auth = authRaw ? JSON.parse(authRaw) : null;
      if (auth?.email) return auth.email;
    } catch {
      // fall through
    }
    return window.localStorage.getItem('admin_email') ||
      window.localStorage.getItem('veterinarian_email') ||
      'Unknown';
  }
  const adminEmail = getCurrentEmail();
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const writeHeader = () => {
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('VETERINARY LAMINITIS TRIAL REPORT', pageWidth / 2, 30, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Subject: ${patientData.horse_name}`, pageWidth / 2, 45, { align: 'center' });
    doc.text(`Trial ID: ${patientData.unique_id}`, pageWidth / 2, 55, { align: 'center' });
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 70, { align: 'center' });
    doc.text(`Generated by: ${adminEmail}`, pageWidth / 2, 78, { align: 'center' });
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text('CONFIDENTIAL - FOR REGULATORY USE ONLY', pageWidth / 2, pageHeight - 10, { align: 'center' });
  };

  const addField = (label: string, value: any, lineHeight = 6) => {
    doc.text(`${label}: ${value ?? 'N/A'}`, 20, nextY.current);
    nextY.current += lineHeight;
  };

  const createTable = (columns: string[], rows: any[][]) => {
    autoTable(doc, {
      head: [columns],
      body: rows,
      startY: nextY.current,
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [41, 128, 185] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      margin: { left: 15, right: 15 },
    });
    // jspdf-autotable attaches `lastAutoTable` to the doc instance after each call.
    const lastAutoTable = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable;
    nextY.current = lastAutoTable?.finalY ? lastAutoTable.finalY + 10 : nextY.current + 10;
  };

  const nextY = { current: 35 };
  writeHeader();
  doc.addPage();
  nextY.current = 25;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. TRIAL OVERVIEW', 20, nextY.current);
  nextY.current += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  addField('Horse Name', patientData.horse_name);
  addField('Trial ID', patientData.unique_id);
  addField('Breed', patientData.breed);
  addField('Age', `${patientData.age} years`);
  addField('Sex', patientData.sex);
  addField('Weight', `${patientData.weight} kg`);
  addField('Owner', patientData.owner_name);
  addField('Owner Contact', patientData.owner_contact);
  addField('Enrollment Date', new Date(patientData.enrollment_date).toLocaleDateString());
  addField('Trial Status', patientData.trial_status);
  addField('Laminitis Grade', patientData.laminitis_grade);
  addField('Affected Limbs', patientData.affected_limbs);
  addField('Protocol Start', patientData.protocol_start_time ? new Date(patientData.protocol_start_time).toLocaleString() : 'Not Started');
  addField('Eligibility Verified', patientData.eligibility_verified ? 'Yes' : 'No');

  if (patientData.veterinarian_name) {
    nextY.current += 5;
    doc.setFont('helvetica', 'bold');
    doc.text('Primary Veterinarian:', 20, nextY.current);
    nextY.current += 6;
    doc.setFont('helvetica', 'normal');
    addField('Name', patientData.veterinarian_name);
    addField('Email', patientData.veterinarian_email);
    addField('Hospital', patientData.hospital_affiliation);
    addField('License', patientData.license_number);
  }

  const treatments = patientData.treatments || [];
  const assessments = patientData.assessments || [];
  const labResults = patientData.lab_results || [];
  const clinicalNotes = patientData.clinical_notes || [];
  const videos = clinicalNotes.filter((note: any) => note.video_url && note.video_url.trim() !== '');

  addField('Total Treatments', treatments.length);
  addField('Total Assessments', assessments.length);
  addField('Total Lab Results', labResults.length);
  addField('Total Clinical Notes', clinicalNotes.length);
  addField('Total Videos', videos.length);

  if (treatments.length) {
    doc.addPage();
    nextY.current = 25;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('2. TREATMENT ADMINISTRATION RECORDS', 20, nextY.current);
    nextY.current += 10;
    createTable([
      'DateTime',
      'Dosage',
      'Volume',
      'Route',
      'Protocol Hr',
      'Veterinarian',
      'Notes',
    ],
    treatments.map((t: any) => [
      new Date(t.administration_datetime).toLocaleString(),
      t.dosage_mg ? `${t.dosage_mg} mg` : 'N/A',
      t.total_volume_ml ? `${t.total_volume_ml} mL` : 'N/A',
      t.route,
      t.protocol_hour !== null ? `Hour ${t.protocol_hour}` : 'Pre-Protocol',
      t.veterinarian_name,
      (t.notes || '').substring(0, 30) + ((t.notes || '').length > 30 ? '...' : ''),
    ]));
  }

  if (assessments.length) {
    doc.addPage();
    nextY.current = 25;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('3. CLINICAL ASSESSMENTS', 20, nextY.current);
    nextY.current += 10;
    createTable([
      'DateTime',
      'Obel',
      'Pain',
      'HR',
      'RR',
      'Temp',
      'Protocol',
    ],
    assessments.map((a: any) => [
      new Date(a.assessment_datetime).toLocaleString(),
      a.obel_grade ?? '-',
      a.pain_score ?? '-',
      a.heart_rate ?? '-',
      a.respiratory_rate ?? '-',
      a.temperature !== null ? `${a.temperature}°F` : '-',
      a.protocol_hour !== null ? `Hour ${a.protocol_hour}` : 'Pre',
    ]));
  }

  if (labResults.length) {
    doc.addPage();
    nextY.current = 25;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('4. LABORATORY RESULTS', 20, nextY.current);
    nextY.current += 10;

    labResults.forEach((lab: any, index: number) => {
      if (nextY.current > 250) {
        doc.addPage();
        nextY.current = 25;
      }
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Lab Test ${index + 1}: ${new Date(lab.test_datetime).toLocaleString()}`, 20, nextY.current);
      nextY.current += 6;
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      const labFields = [
        lab.wbc && `WBC: ${lab.wbc} ×10⁹/L`,
        lab.rbc && `RBC: ${lab.rbc} ×10¹²/L`,
        lab.hemoglobin && `Hemoglobin: ${lab.hemoglobin} g/dL`,
        lab.hematocrit && `Hematocrit: ${lab.hematocrit}%`,
        lab.platelets && `Platelets: ${lab.platelets} ×10⁹/L`,
        lab.glucose && `Glucose: ${lab.glucose} mg/dL`,
        lab.creatinine && `Creatinine: ${lab.creatinine} mg/dL`,
        lab.bun && `BUN: ${lab.bun} mg/dL`,
        lab.alt && `ALT: ${lab.alt} U/L`,
        lab.ast && `AST: ${lab.ast} U/L`,
        lab.serum_amyloid_a && `SAA: ${lab.serum_amyloid_a} μg/mL`,
        lab.fibrinogen && `Fibrinogen: ${lab.fibrinogen} mg/dL`,
        lab.lactate && `Lactate: ${lab.lactate} mmol/L`,
      ].filter(Boolean);
      labFields.forEach((field) => {
        doc.text(field as string, 25, nextY.current);
        nextY.current += 4;
      });
      if (lab.additional_notes) {
        nextY.current += 2;
        doc.setFont('helvetica', 'italic');
        doc.text(`Notes: ${lab.additional_notes.substring(0, 80)}`, 25, nextY.current);
        nextY.current += 5;
        doc.setFont('helvetica', 'normal');
      }
      doc.line(20, nextY.current, 190, nextY.current);
      nextY.current += 8;
    });
  }

  if (videos.length) {
    doc.addPage();
    nextY.current = 25;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('5. VIDEO DOCUMENTATION', 20, nextY.current);
    nextY.current += 10;
    videos.forEach((video: any, index: number) => {
      if (nextY.current > 250) {
        doc.addPage();
        nextY.current = 25;
      }
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Video ${index + 1}:`, 20, nextY.current);
      nextY.current += 6;
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(`File: ${video.video_file_name || 'Untitled'}`, 25, nextY.current);
      nextY.current += 5;
      doc.text(`Uploaded: ${new Date(video.created_at).toLocaleString()}`, 25, nextY.current);
      nextY.current += 5;
      doc.text(`By: ${video.veterinarian_name}`, 25, nextY.current);
      nextY.current += 5;
      doc.text(`Description: ${video.note_content}`, 25, nextY.current);
      nextY.current += 5;
      doc.text(`URL: ${video.video_url}`, 25, nextY.current);
      nextY.current += 5;
      if (video.protocol_hour !== null) {
        doc.text(`Protocol Hour: ${video.protocol_hour}`, 25, nextY.current);
        nextY.current += 5;
      }
      doc.line(20, nextY.current, 190, nextY.current);
      nextY.current += 8;
    });
  }

  if (clinicalNotes.filter((note: any) => !note.video_url || note.video_url.trim() === '').length > 0) {
    doc.addPage();
    nextY.current = 25;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('6. CLINICAL NOTES', 20, nextY.current);
    nextY.current += 10;
    clinicalNotes
      .filter((note: any) => !note.video_url || note.video_url.trim() === '')
      .forEach((note: any, index: number) => {
        if (nextY.current > 250) {
          doc.addPage();
          nextY.current = 25;
        }
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(`Note ${index + 1}: ${note.note_type}`, 20, nextY.current);
        nextY.current += 5;
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(`Date: ${new Date(note.created_at).toLocaleString()}`, 25, nextY.current);
        nextY.current += 4;
        doc.text(`By: ${note.veterinarian_name}`, 25, nextY.current);
        nextY.current += 4;
        if (note.protocol_hour !== null) {
          doc.text(`Protocol Hour: ${note.protocol_hour}`, 25, nextY.current);
          nextY.current += 4;
        }
        const noteLines = doc.splitTextToSize(note.note_content, 160);
        noteLines.forEach((line: string) => {
          if (nextY.current > 270) {
            doc.addPage();
            nextY.current = 25;
          }
          doc.text(line, 25, nextY.current);
          nextY.current += 4;
        });
        doc.line(20, nextY.current, 190, nextY.current);
        nextY.current += 6;
      });
  }

  doc.addPage();
  nextY.current = 25;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('7. AUDIT TRAIL', 20, nextY.current);
  nextY.current += 10;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  addField('Report Generated', new Date().toISOString(), 6);
  addField('Generated By', adminEmail, 6);
  addField('Export Type', 'FDA Regulatory Submission - Complete Trial Record', 6);
  addField('Total Data Points', treatments.length + assessments.length + labResults.length + clinicalNotes.length, 6);
  addField('Data Integrity', 'All timestamps and entries verified at export', 6);

  const pageCount = (doc as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('CONFIDENTIAL - FOR REGULATORY USE ONLY', pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 5, { align: 'center' });
    doc.text('Byrock Veterinary Research | PTP-102 Laminitis Clinical Trial', pageWidth / 2, pageHeight - 2, { align: 'center' });
  }

  const timestamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0].replace('T', '_');
  const filename = `TRIAL_${patientData.unique_id || 'UNKNOWN'}_${patientName.replace(/\s+/g, '_')}_${timestamp}.pdf`;
  doc.save(filename);
}
