export type Patient = {
  id: number;
  unique_id?: string;
  horse_name: string;
  age: number;
  breed: string;
  weight: number;
  sex: string;
  owner_name: string;
  owner_contact: string;
  owner_email?: string | null;
  owner_phone?: string | null;
  owner_address?: string | null;
  owner_relationship?: string | null;
  horse_microchip?: string | null;
  enrollment_date: string;
  trial_status: string;
  screening_status?: 'pending_screening' | 'approved' | 'rejected' | 'awaiting_details' | null;
  screening_notes?: string | null;
  screened_by?: string | null;
  screened_at?: string | null;
  eligibility_verified: boolean;
  protocol_start_time?: string | null;
  consent_date: string | null;
  consent_id?: number | null;
  digital_pulse?: string | null;
  hoof_wall_temperature?: string | null;
  coronary_band_condition?: string | null;
  hoof_tester_response?: string | null;
  stance?: string | null;
  gait?: string | null;
  enrollment_heart_rate?: number | null;
  enrollment_respiratory_rate?: number | null;
  enrollment_temperature?: number | null;
  body_condition_score?: number | null;
  profile_picture_url?: string | null;
  enrolled_by_vet_email?: string | null;
  completed_timeline_steps?: string[];
  created_at: string;
  updated_at: string;
  status_history?: { status: string; timestamp: string; admin: string; notes: string }[];
  audit_log?: { action: string; user: string; timestamp: string; details?: string }[];
};
