export type Patient = {
  id: number;
  horse_name: string;
  age: number;
  breed: string;
  weight: number;
  sex: string;
  owner_name: string;
  owner_contact: string;
  enrollment_date: string;
  trial_status: string;
  screening_status?: 'pending_screening' | 'approved' | 'rejected' | null;
  screening_notes?: string | null;
  screened_by?: string | null;
  screened_at?: string | null;
  eligibility_verified: boolean;
  consent_date: string | null;
  digital_pulse?: string | null;
  hoof_wall_temperature?: string | null;
  coronary_band_condition?: string | null;
  hoof_tester_response?: string | null;
  stance?: string | null;
  gait?: string | null;
  enrollment_heart_rate?: number | null;
  enrollment_respiratory_rate?: number | null;
  enrollment_temperature?: number | null;
  body_condition_score?: number | null;
  profile_picture_url?: string | null;
  enrolled_by_vet_email?: string | null;
  created_at: string;
  updated_at: string;
};
