-- Private uploads bucket for secure file storage.
-- Files are uploaded by a server-side handler using the service role key,
-- so RLS mainly protects against direct client access. Downloads are served
-- through short-lived signed URLs generated by the server.

insert into storage.buckets (id, name, public)
values ('private-uploads', 'private-uploads', false)
on conflict (id) do nothing;

-- Only allow authenticated users to read their own objects. Admins can read anything.
-- The `(storage.foldername(name))[4]` parenthesisation is required by the
-- Postgres parser; subscripting a function-call result without parens is a
-- syntax error.
create policy "Users can read their own private uploads"
on storage.objects for select
to authenticated
using (
  (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  or (storage.foldername(name))[4] = auth.uid()::text
);

-- Only allow authenticated users to upload objects into their own user folder.
create policy "Users can upload to their own private folder"
on storage.objects for insert
to authenticated
with check (
  (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  or (storage.foldername(name))[4] = auth.uid()::text
);

-- Users can only delete their own objects; admins can delete any.
create policy "Users can delete their own private uploads"
on storage.objects for delete
to authenticated
using (
  (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  or (storage.foldername(name))[4] = auth.uid()::text
);
