-- Deprecated: consultant users must be created through Supabase Authentication.
--
-- Direct writes to auth.users bypass GoTrue's managed account setup and can
-- leave users unable to sign in. This historical migration is intentionally a
-- no-op. Consultant role/profile metadata is configured with the guarded
-- scripts/configure-consultants.sql helper after the Auth users exist.
