-- Deprecated: consultant identities are managed by Supabase Authentication.
--
-- This migration previously inserted directly into auth.identities. It is now
-- intentionally a no-op so a fresh deployment cannot create a partial GoTrue
-- identity. Create consultant users through Authentication > Users instead.
